# Generated by Django 3.2.3 on 2021-05-21 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=40)),
                ('first_name', models.CharField(max_length=40)),
                ('category', models.CharField(default='Employee', max_length=40)),
                ('mail_box', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='mail_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=80)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application1.employee')),
            ],
        ),
        migrations.CreateModel(
            name='mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_date', models.DateTimeField()),
                ('subject', models.CharField(max_length=200, null=True)),
                ('isReply', models.BooleanField(default=False)),
                ('previous_mail_date', models.DateTimeField(null=True)),
                ('recipient_mail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_mail_id', to='application1.mail_address')),
                ('sender_mail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_mail_id', to='application1.mail_address')),
            ],
        ),
    ]
